# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTableDialog(object):
    def setupUi(self, AddTableDialog):
        AddTableDialog.setObjectName("AddTableDialog")
        AddTableDialog.resize(400, 160)
        self.formLayout = QtWidgets.QFormLayout(AddTableDialog)
        self.formLayout.setObjectName("formLayout")
        self.algorithmLabel = QtWidgets.QLabel(AddTableDialog)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.algorithmLabel)
        self.algorithmInput = QtWidgets.QComboBox(AddTableDialog)
        self.algorithmInput.setObjectName("algorithmInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.algorithmInput)
        self.tableLabel = QtWidgets.QLabel(AddTableDialog)
        self.tableLabel.setObjectName("tableLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tableLabel)
        self.widget = QtWidgets.QWidget(AddTableDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableInput = QtWidgets.QLineEdit(self.widget)
        self.tableInput.setObjectName("tableInput")
        self.horizontalLayout.addWidget(self.tableInput)
        self.testTableButton = QtWidgets.QPushButton(self.widget)
        self.testTableButton.setObjectName("testTableButton")
        self.horizontalLayout.addWidget(self.testTableButton)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddTableDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.pkInput = QtWidgets.QLineEdit(AddTableDialog)
        self.pkInput.setObjectName("pkInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pkInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.pkLabel = QtWidgets.QLabel(AddTableDialog)
        self.pkLabel.setObjectName("pkLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pkLabel)

        self.retranslateUi(AddTableDialog)
        self.buttonBox.accepted.connect(AddTableDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddTableDialog.reject) # type: ignore
        self.testTableButton.clicked.connect(AddTableDialog.testTable) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddTableDialog)

    def retranslateUi(self, AddTableDialog):
        _translate = QtCore.QCoreApplication.translate
        AddTableDialog.setWindowTitle(_translate("AddTableDialog", "Добавление таблицы"))
        self.algorithmLabel.setText(_translate("AddTableDialog", "Алгоритм:"))
        self.tableLabel.setText(_translate("AddTableDialog", "Таблица:"))
        self.testTableButton.setText(_translate("AddTableDialog", "Проверка"))
        self.pkLabel.setText(_translate("AddTableDialog", "Первичный ключ:<br>(по умолчанию id)"))
