# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFileDialog(object):
    def setupUi(self, AddFileDialog):
        AddFileDialog.setObjectName("AddFileDialog")
        AddFileDialog.resize(400, 160)
        self.formLayout = QtWidgets.QFormLayout(AddFileDialog)
        self.formLayout.setObjectName("formLayout")
        self.algorithmLabel = QtWidgets.QLabel(AddFileDialog)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.algorithmLabel)
        self.algorithmInput = QtWidgets.QComboBox(AddFileDialog)
        self.algorithmInput.setObjectName("algorithmInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.algorithmInput)
        self.filePathLabel = QtWidgets.QLabel(AddFileDialog)
        self.filePathLabel.setObjectName("filePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.filePathLabel)
        self.fileControls = QtWidgets.QWidget(AddFileDialog)
        self.fileControls.setObjectName("fileControls")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fileControls)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filePathInput = QtWidgets.QLineEdit(self.fileControls)
        self.filePathInput.setObjectName("filePathInput")
        self.horizontalLayout.addWidget(self.filePathInput)
        self.selectFile = QtWidgets.QPushButton(self.fileControls)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svgIcon/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectFile.setIcon(icon)
        self.selectFile.setObjectName("selectFile")
        self.horizontalLayout.addWidget(self.selectFile)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fileControls)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.watchInput = QtWidgets.QCheckBox(AddFileDialog)
        self.watchInput.setObjectName("watchInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.watchInput)
        self.backupInput = QtWidgets.QCheckBox(AddFileDialog)
        self.backupInput.setObjectName("backupInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.backupInput)

        self.retranslateUi(AddFileDialog)
        self.buttonBox.accepted.connect(AddFileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddFileDialog.reject) # type: ignore
        self.selectFile.clicked.connect(AddFileDialog.showFileDialog) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddFileDialog)

    def retranslateUi(self, AddFileDialog):
        _translate = QtCore.QCoreApplication.translate
        AddFileDialog.setWindowTitle(_translate("AddFileDialog", "Добавление файла"))
        self.algorithmLabel.setText(_translate("AddFileDialog", "Алгоритм:"))
        self.filePathLabel.setText(_translate("AddFileDialog", "Путь:"))
        self.selectFile.setText(_translate("AddFileDialog", "Обзор"))
        self.watchInput.setText(_translate("AddFileDialog", "Отслеживать изменения"))
        self.backupInput.setText(_translate("AddFileDialog", "Создать резервную копию"))
from gui import main_rc
