# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\db_connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBConnectDialog(object):
    def setupUi(self, DBConnectDialog):
        DBConnectDialog.setObjectName("DBConnectDialog")
        DBConnectDialog.resize(320, 240)
        DBConnectDialog.setModal(True)
        self.formLayout_2 = QtWidgets.QFormLayout(DBConnectDialog)
        self.formLayout_2.setContentsMargins(4, 2, 4, 2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.hostLabel = QtWidgets.QLabel(DBConnectDialog)
        self.hostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostInput = QtWidgets.QLineEdit(DBConnectDialog)
        self.hostInput.setObjectName("hostInput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostInput)
        self.buttonBox = QtWidgets.QDialogButtonBox(DBConnectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.dbInput = QtWidgets.QLineEdit(DBConnectDialog)
        self.dbInput.setObjectName("dbInput")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dbInput)
        self.userInput = QtWidgets.QLineEdit(DBConnectDialog)
        self.userInput.setObjectName("userInput")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userInput)
        self.passwordInput = QtWidgets.QLineEdit(DBConnectDialog)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
        self.portLabel = QtWidgets.QLabel(DBConnectDialog)
        self.portLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.dbLabel = QtWidgets.QLabel(DBConnectDialog)
        self.dbLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbLabel.setObjectName("dbLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dbLabel)
        self.userLabel = QtWidgets.QLabel(DBConnectDialog)
        self.userLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.userLabel.setObjectName("userLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.userLabel)
        self.passwordLabel = QtWidgets.QLabel(DBConnectDialog)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.dbmsLabel = QtWidgets.QLabel(DBConnectDialog)
        self.dbmsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dbmsLabel.setObjectName("dbmsLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.dbmsLabel)
        self.dbmsInput = QtWidgets.QComboBox(DBConnectDialog)
        self.dbmsInput.setObjectName("dbmsInput")
        self.dbmsInput.addItem("")
        self.dbmsInput.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dbmsInput)
        self.portInput = QtWidgets.QSpinBox(DBConnectDialog)
        self.portInput.setMinimum(1024)
        self.portInput.setMaximum(65535)
        self.portInput.setObjectName("portInput")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem)

        self.retranslateUi(DBConnectDialog)
        self.dbmsInput.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(DBConnectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DBConnectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DBConnectDialog)
        DBConnectDialog.setTabOrder(self.hostInput, self.portInput)
        DBConnectDialog.setTabOrder(self.portInput, self.dbInput)
        DBConnectDialog.setTabOrder(self.dbInput, self.userInput)
        DBConnectDialog.setTabOrder(self.userInput, self.passwordInput)
        DBConnectDialog.setTabOrder(self.passwordInput, self.dbmsInput)

    def retranslateUi(self, DBConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        DBConnectDialog.setWindowTitle(_translate("DBConnectDialog", "Подключение к БД"))
        self.hostLabel.setText(_translate("DBConnectDialog", "Хост:"))
        self.portLabel.setText(_translate("DBConnectDialog", "Порт:"))
        self.dbLabel.setText(_translate("DBConnectDialog", "База данных:"))
        self.userLabel.setText(_translate("DBConnectDialog", "Пользователь:"))
        self.passwordLabel.setText(_translate("DBConnectDialog", "Пароль:"))
        self.dbmsLabel.setText(_translate("DBConnectDialog", "СУБД:"))
        self.dbmsInput.setItemText(0, _translate("DBConnectDialog", "MySQL"))
        self.dbmsInput.setItemText(1, _translate("DBConnectDialog", "PostgreSQL"))
