# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\table_actions.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableActions(object):
    def setupUi(self, TableActions):
        TableActions.setObjectName("TableActions")
        TableActions.resize(100, 42)
        TableActions.setWindowTitle("")
        TableActions.setAutoFillBackground(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TableActions)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkButton = QtWidgets.QPushButton(TableActions)
        self.checkButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svgIcon/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkButton.setIcon(icon)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_2.addWidget(self.checkButton)
        self.removeButton = QtWidgets.QPushButton(TableActions)
        self.removeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svgIcon/trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon1)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)

        self.retranslateUi(TableActions)
        QtCore.QMetaObject.connectSlotsByName(TableActions)

    def retranslateUi(self, TableActions):
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setToolTip(_translate("TableActions", "Проверить целостность"))
        self.removeButton.setToolTip(_translate("TableActions", "Удалить запись"))
from gui import main_rc
